#!/bin/bash
PYFILEc = kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
#!/usr/bin/bash
python3 import py_compile

py_compile.compile("$PYFILEc")
